services:
    aris_front.menu_builder:
        class: Aris\FrontBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    aris_front.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: aris_front.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: front } # The alias is what is used to retrieve the menu
