<?php

namespace Aris\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ImagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImagesRepository extends EntityRepository
{
    
    public function getSecuencias($name){
        
      
        
        $query = $this->createQueryBuilder('im')
        ->select('DISTINCT im.secuencia')
        ->Where('im.galeria = :name')
        ->setParameter('name', $name)
        ->getQuery();


        
        return $query->getResult();
        
    }
    
}
