curriculo:
    path:     /
    defaults: { _controller: "ArisAdminBundle:Curriculo:index" }

curriculo_new:
    path:     /new
    defaults: { _controller: "ArisAdminBundle:Curriculo:new" }

curriculo_create:
    path:     /create
    defaults: { _controller: "ArisAdminBundle:Curriculo:create" }
    requirements: { _method: post }

curriculo_edit:
    path:     /{id}/edit
    defaults: { _controller: "ArisAdminBundle:Curriculo:edit" }

curriculo_update:
    path:     /{id}/update
    defaults: { _controller: "ArisAdminBundle:Curriculo:update" }
    requirements: { _method: post|put }


   
